import type { NextPage } from "next"
import Head from "next/head"
import { client } from "../graphql/client"
import { COUNTRY_NAMES } from "../graphql/queries/COUNTRY_NAMES"
import { ICountries } from "../types"

import MapView from "../components/MapView/MapView"
import Layout from "../components/Layout/Layout"
import ErrorBox from "../components/ErrorBox/ErrorBox"

export async function getStaticProps() {
  try {
    const data = await client.request(COUNTRY_NAMES)
    return { props: { countries: data.countries } }
  } catch(err) {
    return { props: { error: JSON.stringify(err) } }
  }
}

interface IPageProps {
  countries?: ICountries
  error?: string
}

const HomePage: NextPage<IPageProps> = (props) => {
  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="An interactive map that contains information about countries. Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {Array.isArray(props.countries)
          ? <MapView countries={props.countries} />
          : <ErrorBox error={props.error as string} />
        }
      </Layout>
    </>
  )
}

export default HomePage